import { RENPY_DOC_BASE } from "./constants";

/** Script keywords and topics not covered by the generated Sphinx indexes */
export const EXTRA_DOC_LINKS: Record<string, string> = {
  label: `${RENPY_DOC_BASE}label.html#label-statement`,
  jump: `${RENPY_DOC_BASE}label.html#jump-statement`,
  call: `${RENPY_DOC_BASE}label.html#call-statement`,
  return: `${RENPY_DOC_BASE}label.html#return-statement`,
  pass: `${RENPY_DOC_BASE}conditional.html#pass-statement`,
  menu: `${RENPY_DOC_BASE}menus.html#in-game-menus`,
  scene: `${RENPY_DOC_BASE}displaying_images.html#scene-statement`,
  show: `${RENPY_DOC_BASE}displaying_images.html#show-statement`,
  hide: `${RENPY_DOC_BASE}displaying_images.html#hide-statement`,
  with: `${RENPY_DOC_BASE}transitions.html#with-statement`,
  window: `${RENPY_DOC_BASE}dialogue.html#window`,
  play: `${RENPY_DOC_BASE}audio.html#play-statement`,
  queue: `${RENPY_DOC_BASE}audio.html#queue-statement`,
  stop: `${RENPY_DOC_BASE}audio.html#stop-statement`,
  python: `${RENPY_DOC_BASE}python.html`,
  init: `${RENPY_DOC_BASE}python.html#init-python-statement`,
  define: `${RENPY_DOC_BASE}python.html#define-statement`,
  default: `${RENPY_DOC_BASE}python.html#default-statement`,
  transform: `${RENPY_DOC_BASE}transforms.html`,
  image: `${RENPY_DOC_BASE}displaying_images.html#image-statement`,
  screen: `${RENPY_DOC_BASE}screens.html`,
  zorder: `${RENPY_DOC_BASE}displaying_images.html#zorder-statement`,
  on: `${RENPY_DOC_BASE}displaying_images.html#on-statement`,
  voice: `${RENPY_DOC_BASE}voice.html`,
  movie: `${RENPY_DOC_BASE}movie.html`,
  pause: `${RENPY_DOC_BASE}quickstart.html#pause-statement`,
  camera: `${RENPY_DOC_BASE}3dstage.html`,
  translate: `${RENPY_DOC_BASE}translation.html`,
  if: `${RENPY_DOC_BASE}conditional.html#if-statement`,
  elif: `${RENPY_DOC_BASE}conditional.html#if-statement`,
  else: `${RENPY_DOC_BASE}conditional.html#if-statement`,
  while: `${RENPY_DOC_BASE}conditional.html#while-statement`,
  $: `${RENPY_DOC_BASE}python.html#python-statement`,
};
